name: update_power_outage_map
on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  update_power_outage_map:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./power-outages
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Execute python script
        run: |
          python power-outages/convert.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m 'cron: updates power outage data'
          git push
